sudo: false
language: node_js
node_js:
  - '6'
  - '8'
compiler: clang-3.6
env:
  - CXX=clang-3.6
addons:
  apt:
    sources:
      #- llvm-toolchain-precise-3.6
      - ubuntu-toolchain-r-test
    packages:
      - unzip
      #- clang-3.6
      - clang
      - g++-4.8
script: ./travis.sh
cache:
  directories:
  - cli/.flow-bins-cache
